---
title: "Dynamic SEM on ESM Data"
author: "MohammadHossein Manuel Haqiqatkhah - R0607671"
date: '2019-08-23'
output:
  html_document:
    df_print: paged
subtitle: Structural Equation Modeling Course Project - KU Leuven
bibliography: ref.bib
---


```{r setup, include = FALSE, echo = FALSE}
list.of.packages <- c("tidyverse",
                      "plyr",
                      "qgraph",
                      "dplyr",
                      "kable",
                      "kableExtra",
                      "semPlot",
                      "lavaan")
new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages)) {
  install.packages(new.packages, repos='http://cran.us.r-project.org')
}
tmp <- lapply(list.of.packages, require, character.only = TRUE)

rm(list.of.packages, new.packages, tmp)
knitr::opts_chunk$set(echo = FALSE)

# rm(list = ls())

```

```{r handy-functions}

pagebreak <- function(){
  if(knitr::is_latex_output())
    return("\\newpage")
  else
    return('<div style="page-break-before: always;" />')
}

```


```{r model-making}

make.factors <- function(items,
                         factor.name = "f",
                         add.factor.name = TRUE,
                         num.times = 2,
                         skip.first = 0,
                         substr.length = 3){
  factor.postfix <- ""

  if(add.factor.name) factor.postfix <- paste0(".",factor.name)
  loadings <- items %>%
    substring(skip.first + 1, skip.first + substr.length) %>%
    paste0(factor.postfix, "*")
  loadings[1] <- "1*"
  
  out <- c()  
  for(time in 1:num.times){
    items.here <- items %>% paste0(".",time)
    RHS.string <- paste(loadings, items.here, sep = "", collapse = " + ")
    factor.string <- paste(factor.name, ".", time, " =~ ",
                           RHS.string, sep = "")
    out <- out %>% c(factor.string)
  }
  out <- out %>% paste(sep = "", collapse = " + ")
  out %>% return()
}

ar <- function(items, op = "~"){
  paste(paste0(items,".2"),op, paste0(items,".1"))
}

my.lav.model.maker <- function(inp.lagged,
                               add.resid.serial.AR = TRUE,
                               add.resid.serial.COV = FALSE,
                               add.posneg = TRUE,
                               add.posneg.AR = TRUE,
                               add.communal.VAR = TRUE,
                               add.factor.COV = TRUE,
                               communal.names = c("f","g")){
  
  # add = c("residAR", "factorVAR", "residCOR")
  
  model.strings <- c()
  
  # building lists of items
  items.pos <- inp.lagged$items.pos
  items.neg <- inp.lagged$items.neg
  items.all <- inp.lagged$items.all
  

  # AR/AC terms
  if(add.resid.serial.AR | add.resid.serial.COV){
    op <- " ~ "
    if(add.resid.serial.COV) op <- " ~~ "
    added.string <- items.all %>% ar(op)
    model.strings <- model.strings %>% c(added.string)
  }
  
  # factor terms
  if(add.posneg){
    pos.string <- items.pos %>% make.factors(factor.name = "pos")
    neg.string <- items.neg %>% make.factors(factor.name = "neg")
    model.strings <- model.strings %>% c(pos.string, neg.string)
  }
  
  for(f.name in communal.names){
    added.string <- items.all %>% make.factors(factor.name = f.name)
    model.strings <- model.strings %>% c(added.string)
  }
  model.strings %>% return()
}


my.lagger <- function(input,
                      items,
                      identifiers = NULL){
    
  cnames.1 <- items %>% paste0(".1")
  cnames.2 <- items %>% paste0(".2")

  d.items <- input %>%
    select(items)
  d.identifiers <- input %>%
    select(identifiers)
  
  d.lagged <- d.items[-1,] %>% 
    rbind(NA)

  d.out <- cbind(d.identifiers, d.items, d.lagged)
  colnames(d.out) <- c(identifiers, cnames.1, cnames.2)

  d.out %>% return()
}

```


# Introduction

Experience sampling method (ESM)

```{r data-prep}

# load data
data.orig <- read.csv("https://raw.githubusercontent.com/psyguy/sem-course-project/master/data/ESMdata.csv")


identif <- c("concentrat",
                   "dayno",
                   "beepno"
                   )
items <- list(
              anxiety = c("anxious",
                           "doubt",
                           "guilty",
                           "lonely",
                           "suspic",
                           "worry"
                           ),
              
              selfcon = c("ashamed",
                           "lonely",
                           "guilty",
                           "selfdoub",
                           "worry"
                           ),
              
              somatiz = c("dizzy",
                           "drymouth",
                           "headache",
                           "nauseous",
                           "sleepy",
                           "tired"
                           ),
              
              posacti = c("cheerf",
                           "concent",
                           "enjoy",
                           "enthus",
                           "relaxed",
                           "satisfi",
                           "strong"
                           ),
              
              negacti = c("agitate",
                           "down",
                           "irritat",
                           "restl",
                           "sleepy"
                           )
              )

# Epskamp
items <- list(
              anxiety = c("anxious",
                           "guilty",
                           "lonely"
                           ),

              selfcon = c("ashamed",
                           "lonely",
                           "guilty",
                           "worry"
                           ),

              somatiz = c(#"dizzy",
                           #"drymouth",
                           "headache",
                           #"nauseous",
                           "sleepy",
                           "tired"
                           ),

              posacti = c(#"cheerf",
                           #"concent",
                           #"enjoy",
                           "enthus",
                           #"relaxed",
                           "satisfi",
                           "sleepy",
                           "strong"
                           ),

              negacti = c("agitate",
                           #"down",
                           "irritat",
                           "restl",
                           "sleepy"
                           )
              )

noniden <- items %>%
  unlist() %>% 
  unique() %>% 
  sort()

data <- data.orig %>% 
  select(-contains("_med")) %>% 
  filter(beepno ==5)
colnames(data) <- gsub(".*_", "", colnames(data))
d <- data %>% select(identif, noniden)

```


```{r model-syntax, include=TRUE, echo=TRUE}

m <- list()

for(i in 1:length(items)){
  f.name <- names(items)[[i]]
  m[[i]] <- make.factors(items = items[[i]],
                       factor.name = f.name,
                       num.times = 1)
  names(m)[[i]] <- f.name
}

# mm <- m %>% paste(collapse = " \n \n ") %>% cat( )

dl <- d %>% my.lagger(items = noniden)

dl.1 <- dl %>% select(contains(".1")) %>% na.omit()
p <- dl.1 %>% princomp(3)

e <- psych::fa(dl.1, 5)

```

```{r model-fitting}

mm <- "
# anxiety.1 =~ 1*anxious.1 + gui.anxiety*guilty.1 + lon.anxiety*lonely.1 
#  
#  selfcon.1 =~ 1*ashamed.1 + lon.selfcon*lonely.1 + gui.selfcon*guilty.1 + wor.selfcon*worry.1 
#  
#  somatiz.1 =~ 1*headache.1 + sle.somatiz*sleepy.1 + tir.somatiz*tired.1 
#  
 posacti.1 =~ 1*enthus.1 + sat.posacti*satisfi.1 + sle.posacti*sleepy.1 + str.posacti*strong.1 
 
 negacti.1 =~ 1*agitate.1 + irr.negacti*irritat.1 + res.negacti*restl.1 + sle.negacti*sleepy.1

# anxiety.1 ~~ selfcon.1 +  posacti.1 + negacti.1 + somatiz.1
posacti.1 ~~ negacti.1
# anxiety.1 ~~ 1*anxiety.1
# selfcon.1 ~~ 1*selfcon.1
# somatiz.1 ~~ 1*somatiz.1
posacti.1 ~~ 1*posacti.1
negacti.1 ~~ 1*negacti.1
 
 # anxious.1 ~~ anxious.1
 # doubt.1 ~~ doubt.1
 # guilty.1 ~~ guilty.1
 # lonely.1 ~~ lonely.1
 # suspic.1 ~~ suspic.1
 # worry.1 ~~ worry.1


"

f <- cfa(mm, na.omit(dl), std.lv = TRUE)#, ordered = colnames(dl))

f %>% summary(standardized=TRUE)
f %>% fitmeasures()

inspect(f, what = "std.lv")$psi
# f %>% modificationindices() %>% as.data.frame() %>% group_by(mi)
# x$psi
# dl %>% na.omit %>% cor() %>% eigen()
```


