---
title: "Dynamic SEM on ESM Data"
subtitle: "Structural Equation Modeling Course Project - KU Leuven"
author: "MohammadHossein Manuel Haqiqatkhah - R0607671"
date: "2019-08-19"
bibliography: ref.bib
output: pdf_document
---


```{r setup, include = FALSE, echo = FALSE}
list.of.packages <- c("tidyverse",
                      "plyr",
                      "qgraph",
                      "dplyr",
                      "lavaan")
new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages)) {
  install.packages(new.packages, repos='http://cran.us.r-project.org')
}
tmp <- lapply(list.of.packages, require, character.only = TRUE)

rm(list.of.packages, new.packages, tmp)
knitr::opts_chunk$set(echo = FALSE)

```

```{r handy-functions}

pagebreak <- function(){
  if(knitr::is_latex_output())
    return("\\newpage")
  else
    return('<div style="page-break-before: always;" />')
}

```


# Introduction

Experience sampling method (ESM)



```{r cars}
library(lavaan)

# load/prep data
data <- read.table("http://www.statmodel.com/usersguide/chap5/ex5.8.dat")
names(data) <- c(paste("y", 1:6, sep=""), paste("x", 1:3, sep=""))

# model 1 - canonical mimic model (using the '~' regression operator)
model1 <- '
    f1 =~ y1 + y2 + y3
    f1 ~ x1 + x2 + x3
'

# model 2 - seemingly the same (using the '<~' composite operator)
model2 <- '
    f1 =~ y1 + y2 + y3
    # f1 <~ x1 + x2 + x3
'
# model 3 - only reflective
model3 <- '
    f1 =~ y1 + y2 + y3
    # f1 <~ x1 + x2 + x3
'
# model 4 - only formative
model4 <- '
    f1 ~ y1 + y2 + y3
    # f1 <~ x1 + x2 + x3
'

# run lavaan
fit1 <- sem(model1, data=data, std.lv=TRUE)
fit2 <- sem(model2, data=data, std.lv=TRUE)
fit3 <- sem(model3, data=data, std.lv=TRUE)
fit4 <- sem(model4, data=data, std.lv=TRUE)

# test equality - only the operators are different
all.equal(parameterEstimates(fit1), parameterEstimates(fit2))
```





## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



```{r writing-bib}
bib <- "



"

writeLines(bib, con = "ref.bib")
```
